-- Alte Objekte löschen
DROP VIEW IF EXISTS "ÄhnlicheProdukteBidirektional" CASCADE;
DROP VIEW IF EXISTS "ProduktDurchschnittsRating" CASCADE;
DROP FUNCTION IF EXISTS "aktualisiere_produkt_rating"() CASCADE;
DROP TABLE IF EXISTS "Ladefehler" CASCADE;
DROP TABLE IF EXISTS "Kundenrezension" CASCADE;
DROP TABLE IF EXISTS "Kaufposition" CASCADE;
DROP TABLE IF EXISTS "Kauf" CASCADE;
DROP TABLE IF EXISTS "Kunde" CASCADE;
DROP TABLE IF EXISTS "Konditionen" CASCADE;
DROP TABLE IF EXISTS "Filiale" CASCADE;
DROP TABLE IF EXISTS "Produktaudio" CASCADE;
DROP TABLE IF EXISTS "ProduktListmania" CASCADE;
DROP TABLE IF EXISTS "Produktstudios" CASCADE;
DROP TABLE IF EXISTS "Beteiligte Künstler" CASCADE;
DROP TABLE IF EXISTS "Beteiligte Personen" CASCADE;
DROP TABLE IF EXISTS "Buchautoren" CASCADE;
DROP TABLE IF EXISTS "MusikCDLabels" CASCADE;
DROP TABLE IF EXISTS "Buchverlage" CASCADE;
DROP TABLE IF EXISTS "Produktähnlichkeit" CASCADE;
DROP TABLE IF EXISTS "Produktkategorien" CASCADE;
DROP TABLE IF EXISTS "Kategorie" CASCADE;
DROP TABLE IF EXISTS "Lied" CASCADE;
DROP TABLE IF EXISTS "Musik-CD" CASCADE;
DROP TABLE IF EXISTS "DVD" CASCADE;
DROP TABLE IF EXISTS "Buch" CASCADE;
DROP TABLE IF EXISTS "Produkt" CASCADE;
DROP TABLE IF EXISTS "Künstler" CASCADE;
DROP TABLE IF EXISTS "Director" CASCADE;
DROP TABLE IF EXISTS "Creator" CASCADE;
DROP TABLE IF EXISTS "Autor" CASCADE;
DROP TABLE IF EXISTS "Actor" CASCADE;
DROP TABLE IF EXISTS "Person" CASCADE;
DROP TABLE IF EXISTS "ListmaniaListe" CASCADE;
DROP TABLE IF EXISTS "Studio" CASCADE;
DROP TABLE IF EXISTS "Label" CASCADE;
DROP TABLE IF EXISTS "Verlag" CASCADE;
-- Referenztabellen
CREATE TABLE "Verlag" (
    "VerlagID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Verlagname" VARCHAR(255) NOT NULL
);
CREATE TABLE "Label" (
    "LabelID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Labelname" VARCHAR(255) NOT NULL
);
CREATE TABLE "Studio" (
    "StudioID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Studioname" VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE "ListmaniaListe" (
    "ListmaniaID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(255) NOT NULL UNIQUE
);
-- Personen und Rollen
CREATE TABLE "Person" (
    "PersonID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(255) NOT NULL
);
CREATE TABLE "Actor" (
    "PersonID" INTEGER PRIMARY KEY,
    CONSTRAINT "actor_personid_fk" FOREIGN KEY ("PersonID") REFERENCES "Person" ("PersonID") ON DELETE CASCADE
);
CREATE TABLE "Autor" (
    "PersonID" INTEGER PRIMARY KEY,
    CONSTRAINT "autor_personid_fk" FOREIGN KEY ("PersonID") REFERENCES "Person" ("PersonID") ON DELETE CASCADE
);
CREATE TABLE "Creator" (
    "PersonID" INTEGER PRIMARY KEY,
    CONSTRAINT "creator_personid_fk" FOREIGN KEY ("PersonID") REFERENCES "Person" ("PersonID") ON DELETE CASCADE
);
CREATE TABLE "Director" (
    "PersonID" INTEGER PRIMARY KEY,
    CONSTRAINT "director_personid_fk" FOREIGN KEY ("PersonID") REFERENCES "Person" ("PersonID") ON DELETE CASCADE
);
CREATE TABLE "Künstler" (
    "PersonID" INTEGER PRIMARY KEY,
    CONSTRAINT "kuenstler_personid_fk" FOREIGN KEY ("PersonID") REFERENCES "Person" ("PersonID") ON DELETE CASCADE
);
-- Produkte
CREATE TABLE "Produkt" (
    "Produktnummer" VARCHAR(20) PRIMARY KEY,
    "Titel" TEXT NOT NULL,
    -- Könnte man noch unique machen, aber das wäre evtl. zu streng
    "Verkaufsrang" INTEGER NULL,
    "Bild" TEXT NULL,
    "Detailseite" TEXT NULL,
    "EAN" TEXT NULL,
    -- Jedes Produkt muss von einem bestimmten Typ sein. Evtl zu streng?
    "Produkttyp" VARCHAR(20) NOT NULL,
    -- Durchschnitt aller Rezensionspunkte; wird per Trigger auf "Kundenrezension" aktuell gehalten (siehe unten)
    "Durchschnittsbewertung" NUMERIC(3, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT "produkt_nummer_not_blank_check" CHECK (length(trim("Produktnummer")) > 0),
    CONSTRAINT "produkt_durchschnittsbewertung_check" CHECK (
        "Durchschnittsbewertung" BETWEEN 0 AND 5
    ),
    CONSTRAINT "produkt_verkaufsrang_check" CHECK (
        "Verkaufsrang" IS NULL
        OR "Verkaufsrang" > 0
    ),
    CONSTRAINT "produkt_typ_check" CHECK ("Produkttyp" IN ('Buch', 'Musik-CD', 'DVD'))
);
CREATE TABLE "Buch" (
    "Produktnummer" VARCHAR(20) PRIMARY KEY,
    "Seitenzahl" INTEGER NULL,
    "Erscheinungsdatum" DATE NULL,
    "ISBN-Nummer" TEXT NOT NULL UNIQUE,
    "Bindung" TEXT NULL,
    "Auflage" TEXT NULL,
    "Paketgewicht" NUMERIC(10, 2) NULL,
    "Pakethoehe" NUMERIC(10, 2) NULL,
    "Paketlaenge" NUMERIC(10, 2) NULL,
    CONSTRAINT "buch_seitenzahl_check" CHECK (
        "Seitenzahl" IS NULL
        OR "Seitenzahl" > 0
    ),
    CONSTRAINT "buch_produktnummer_fk" FOREIGN KEY ("Produktnummer") REFERENCES "Produkt" ("Produktnummer") ON DELETE CASCADE
);
CREATE TABLE "Musik-CD" (
    "Produktnummer" VARCHAR(20) PRIMARY KEY,
    "Erscheinungsdatum" DATE NULL,
    "Bindung" TEXT NULL,
    "Format" TEXT NULL,
    "AnzahlDiscs" INTEGER NULL,
    "UPC" TEXT NULL,
    CONSTRAINT "musik_cd_anzahl_discs_check" CHECK (
        "AnzahlDiscs" IS NULL
        OR "AnzahlDiscs" > 0
    ),
    CONSTRAINT "musik_cd_produktnummer_fk" FOREIGN KEY ("Produktnummer") REFERENCES "Produkt" ("Produktnummer") ON DELETE CASCADE
);
CREATE TABLE "Lied" (
    "LiedID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Produktnummer" VARCHAR(20) NOT NULL,
    "Tracknummer" INTEGER NULL,
    "Name" TEXT NOT NULL,
    CONSTRAINT "lied_tracknummer_check" CHECK (
        "Tracknummer" IS NULL
        OR "Tracknummer" > 0
    ),
    CONSTRAINT "lied_produktnummer_name_unique" UNIQUE ("Produktnummer", "Name"),
    CONSTRAINT "lied_produktnummer_tracknummer_unique" UNIQUE ("Produktnummer", "Tracknummer"),
    CONSTRAINT "lied_produktnummer_fk" FOREIGN KEY ("Produktnummer") REFERENCES "Musik-CD" ("Produktnummer") ON DELETE CASCADE
);
CREATE TABLE "DVD" (
    "Produktnummer" VARCHAR(20) PRIMARY KEY,
    "Format" VARCHAR(255) NULL,
    "Laufzeit" INTERVAL NULL,
    "Region Code" INTEGER NULL,
    "Erscheinungsdatum" DATE NULL,
    "AspectRatio" TEXT NULL,
    "TheatricalRelease" TEXT NULL,
    "UPC" TEXT NULL,
    CONSTRAINT "dvd_laufzeit_check" CHECK (
        "Laufzeit" IS NULL
        OR "Laufzeit" > INTERVAL '0 seconds'
    ),
    CONSTRAINT "dvd_region_code_check" CHECK (
        "Region Code" IS NULL
        OR "Region Code" >= 0
    ),
    CONSTRAINT "dvd_produktnummer_fk" FOREIGN KEY ("Produktnummer") REFERENCES "Produkt" ("Produktnummer") ON DELETE CASCADE
);
-- Kategorien
CREATE TABLE "Kategorie" (
    "KategorieID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(255) NOT NULL,
    "Pfad" TEXT NOT NULL UNIQUE,
    "OberkategorieID" INTEGER NULL,
    -- Oberkategorie kann nicht sich selbst referenzieren
    CONSTRAINT "kategorie_oberkategorie_not_self_check" CHECK (
        "OberkategorieID" IS NULL
        OR "OberkategorieID" <> "KategorieID"
    ),
    -- Überprüfen der Fremdschlüsselbedingung bis zum Commit aufschieben, damit Eltern und Kindreferenzen in beliebiger Reihenfolge innerhalb einer Transaktion eingefügt werden können
    CONSTRAINT "kategorie_oberkategorie_fk" FOREIGN KEY ("OberkategorieID") REFERENCES "Kategorie" ("KategorieID") DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE "Produktkategorien" (
    "Produktnummer" VARCHAR(20) NOT NULL,
    "KategorieID" INTEGER NOT NULL,
    PRIMARY KEY ("Produktnummer", "KategorieID"),
    CONSTRAINT "produktkategorien_kategorie_fk" FOREIGN KEY ("KategorieID") REFERENCES "Kategorie" ("KategorieID") ON DELETE CASCADE,
    CONSTRAINT "produktkategorien_produkt_fk" FOREIGN KEY ("Produktnummer") REFERENCES "Produkt" ("Produktnummer") ON DELETE CASCADE
);
-- Beziehungen
CREATE TABLE "Buchautoren" (
    "BuchID" VARCHAR(20) NOT NULL,
    "AutorID" INTEGER NOT NULL,
    PRIMARY KEY ("BuchID", "AutorID"),
    CONSTRAINT "buchautoren_autorid_fk" FOREIGN KEY ("AutorID") REFERENCES "Autor" ("PersonID") ON DELETE CASCADE,
    CONSTRAINT "buchautoren_buchid_fk" FOREIGN KEY ("BuchID") REFERENCES "Buch" ("Produktnummer") ON DELETE CASCADE
);
-- In den Daten kommen mehrere Buchverläge bzw Labels vor
CREATE TABLE "Buchverlage" (
    "BuchID" VARCHAR(20) NOT NULL,
    "VerlagID" INTEGER NOT NULL,
    PRIMARY KEY ("BuchID", "VerlagID"),
    CONSTRAINT "buchverlage_buch_fk" FOREIGN KEY ("BuchID") REFERENCES "Buch" ("Produktnummer") ON DELETE CASCADE,
    CONSTRAINT "buchverlage_verlag_fk" FOREIGN KEY ("VerlagID") REFERENCES "Verlag" ("VerlagID") ON DELETE CASCADE
);
CREATE TABLE "MusikCDLabels" (
    "Produktnummer" VARCHAR(20) NOT NULL,
    "LabelID" INTEGER NOT NULL,
    PRIMARY KEY ("Produktnummer", "LabelID"),
    CONSTRAINT "musik_cd_labels_musik_cd_fk" FOREIGN KEY ("Produktnummer") REFERENCES "Musik-CD" ("Produktnummer") ON DELETE CASCADE,
    CONSTRAINT "musik_cd_labels_label_fk" FOREIGN KEY ("LabelID") REFERENCES "Label" ("LabelID") ON DELETE CASCADE
);
CREATE TABLE "Beteiligte Personen" (
    "Produktnummer" VARCHAR(20) NOT NULL,
    "PersonID" INTEGER NOT NULL,
    "Rolle" VARCHAR(50) NOT NULL,
    PRIMARY KEY ("Produktnummer", "PersonID", "Rolle"),
    CONSTRAINT "beteiligte_personen_rolle_check" CHECK ("Rolle" IN ('Actor', 'Creator', 'Director')),
    CONSTRAINT "beteiligte_personen_person_fk" FOREIGN KEY ("PersonID") REFERENCES "Person" ("PersonID") ON DELETE CASCADE,
    CONSTRAINT "beteiligte_personen_produkt_fk" FOREIGN KEY ("Produktnummer") REFERENCES "DVD" ("Produktnummer") ON DELETE CASCADE
);
CREATE TABLE "Beteiligte Künstler" (
    "Produktnummer" VARCHAR(20) NOT NULL,
    "KünstlerID" INTEGER NOT NULL,
    PRIMARY KEY ("Produktnummer", "KünstlerID"),
    CONSTRAINT "beteiligte_kuenstler_kuenstler_fk" FOREIGN KEY ("KünstlerID") REFERENCES "Künstler" ("PersonID") ON DELETE CASCADE,
    CONSTRAINT "beteiligte_kuenstler_produkt_fk" FOREIGN KEY ("Produktnummer") REFERENCES "Musik-CD" ("Produktnummer") ON DELETE CASCADE
);
CREATE TABLE "Produktähnlichkeit" (
    "Produktnummer1" VARCHAR(20) NOT NULL,
    "Produktnummer2" VARCHAR(20) NOT NULL,
    "ÄhnlicherTitel" TEXT NULL,
    PRIMARY KEY ("Produktnummer1", "Produktnummer2"),
    CONSTRAINT "produktaehnlichkeit_order_check" CHECK ("Produktnummer1" < "Produktnummer2"),
    CONSTRAINT "produktaehnlichkeit_p1_fk" FOREIGN KEY ("Produktnummer1") REFERENCES "Produkt" ("Produktnummer") ON DELETE CASCADE,
    CONSTRAINT "produktaehnlichkeit_p2_fk" FOREIGN KEY ("Produktnummer2") REFERENCES "Produkt" ("Produktnummer") ON DELETE CASCADE
);
CREATE TABLE "Produktstudios" (
    "Produktnummer" VARCHAR(20) NOT NULL,
    "StudioID" INTEGER NOT NULL,
    PRIMARY KEY ("Produktnummer", "StudioID"),
    CONSTRAINT "produktstudios_produkt_fk" FOREIGN KEY ("Produktnummer") REFERENCES "Produkt" ("Produktnummer") ON DELETE CASCADE,
    CONSTRAINT "produktstudios_studio_fk" FOREIGN KEY ("StudioID") REFERENCES "Studio" ("StudioID") ON DELETE CASCADE
);
CREATE TABLE "ProduktListmania" (
    "Produktnummer" VARCHAR(20) NOT NULL,
    "ListmaniaID" INTEGER NOT NULL,
    PRIMARY KEY ("Produktnummer", "ListmaniaID"),
    CONSTRAINT "produktlistmania_produkt_fk" FOREIGN KEY ("Produktnummer") REFERENCES "Produkt" ("Produktnummer") ON DELETE CASCADE,
    CONSTRAINT "produktlistmania_liste_fk" FOREIGN KEY ("ListmaniaID") REFERENCES "ListmaniaListe" ("ListmaniaID") ON DELETE CASCADE
);
CREATE TABLE "Produktaudio" (
    "Produktnummer" VARCHAR(20) NOT NULL,
    "Sprache" TEXT NOT NULL,
    "Sprachtyp" TEXT NOT NULL DEFAULT '',
    "Audioformat" TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (
        "Produktnummer",
        "Sprache",
        "Sprachtyp",
        "Audioformat"
    ),
    CONSTRAINT "produktaudio_produkt_fk" FOREIGN KEY ("Produktnummer") REFERENCES "Produkt" ("Produktnummer") ON DELETE CASCADE
);
-- Einzelhandel
CREATE TABLE "Filiale" (
    "FilialeID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(255) NOT NULL UNIQUE,
    "Anschrift" VARCHAR(255) NOT NULL,
    "Ort" VARCHAR(255) NOT NULL
);
CREATE TABLE "Konditionen" (
    "FilialeID" INTEGER NOT NULL,
    "Produktnummer" VARCHAR(20) NOT NULL,
    "Zustand" VARCHAR(255) NOT NULL,
    "Preis" NUMERIC(10, 2) NULL,
    "Verfügbarkeit" BOOLEAN NOT NULL DEFAULT TRUE,
    "Währung" VARCHAR(10) NULL,
    PRIMARY KEY ("FilialeID", "Produktnummer", "Zustand"),
    CONSTRAINT "konditionen_preis_check" CHECK (
        "Preis" IS NULL
        OR "Preis" >= 0
    ),
    CONSTRAINT "konditionen_filiale_fk" FOREIGN KEY ("FilialeID") REFERENCES "Filiale" ("FilialeID") ON DELETE CASCADE,
    CONSTRAINT "konditionen_produkt_fk" FOREIGN KEY ("Produktnummer") REFERENCES "Produkt" ("Produktnummer") ON DELETE CASCADE
);
-- Verkauf und Rezensionen
CREATE TABLE "Kunde" (
    "KundeID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(255) NOT NULL UNIQUE,
    "Lieferadresse" VARCHAR(255) NULL,
    "Kontonummer" VARCHAR(50) NULL UNIQUE
);
CREATE TABLE "Kauf" (
    "KaufID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "KundeID" INTEGER NOT NULL,
    "Zeitpunkt" TIMESTAMP NOT NULL,
    CONSTRAINT "kauf_kunde_fk" FOREIGN KEY ("KundeID") REFERENCES "Kunde" ("KundeID")
);
CREATE TABLE "Kaufposition" (
    "KaufID" INTEGER NOT NULL,
    "PositionID" INTEGER NOT NULL,
    "FilialeID" INTEGER NOT NULL,
    "Produktnummer" VARCHAR(20) NOT NULL,
    "Zustand" VARCHAR(255) NOT NULL,
    "Kaufpreis" NUMERIC(10, 2) NOT NULL,
    PRIMARY KEY ("KaufID", "PositionID"),
    CONSTRAINT "kaufposition_kaufpreis_check" CHECK ("Kaufpreis" >= 0),
    CONSTRAINT "kaufposition_kauf_fk" FOREIGN KEY ("KaufID") REFERENCES "Kauf" ("KaufID") ON DELETE CASCADE,
    CONSTRAINT "kaufposition_konditionen_fk" FOREIGN KEY ("FilialeID", "Produktnummer", "Zustand") REFERENCES "Konditionen" ("FilialeID", "Produktnummer", "Zustand")
);
CREATE TABLE "Kundenrezension" (
    "RezensionID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "KundeID" INTEGER NOT NULL,
    "Produktnummer" VARCHAR(20) NOT NULL,
    "Rezensionsdatum" DATE NULL,
    "Helpful" INTEGER NULL,
    "Summary" TEXT NULL,
    "Text" TEXT NOT NULL,
    "Punkte" INTEGER NOT NULL,
    CONSTRAINT "kundenrezension_punkte_check" CHECK (
        "Punkte" BETWEEN 1 AND 5
    ),
    CONSTRAINT "kundenrezension_helpful_check" CHECK (
        "Helpful" IS NULL
        OR "Helpful" >= 0
    ),
    -- Jeder Kunde kann nur eine Rezension für ein Produkt abgeben
    CONSTRAINT "kundenrezension_kunde_produkt_unique" UNIQUE ("KundeID", "Produktnummer"),
    CONSTRAINT "kundenrezension_kunde_fk" FOREIGN KEY ("KundeID") REFERENCES "Kunde" ("KundeID"),
    CONSTRAINT "kundenrezension_produkt_fk" FOREIGN KEY ("Produktnummer") REFERENCES "Produkt" ("Produktnummer") ON DELETE CASCADE
);
CREATE TABLE "Ladefehler" (
    "FehlerID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Entity" VARCHAR(100) NOT NULL,
    "Attribut" VARCHAR(100) NOT NULL,
    "Rohwert" TEXT NULL,
    "Quelle" TEXT NOT NULL,
    "Meldung" TEXT NOT NULL,
    "ErfasstAm" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- jetzt als Trigger statt View
-- Betroffen ist bei INSERT das neue, bei DELETE das alte Produkt und bei UPDATE beide, falls die Rezension einem anderen Produkt zugeordnet wurde
CREATE FUNCTION "aktualisiere_produkt_rating"() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
UPDATE "Produkt" p
SET "Durchschnittsbewertung" = COALESCE(
        (
            SELECT round(avg(k."Punkte")::numeric, 2)
            FROM "Kundenrezension" k
            WHERE k."Produktnummer" = p."Produktnummer"
        ),
        0.00
    )
WHERE p."Produktnummer" = ANY (
        CASE
            TG_OP
            WHEN 'INSERT' THEN ARRAY [NEW."Produktnummer"]
            WHEN 'DELETE' THEN ARRAY [OLD."Produktnummer"]
            ELSE ARRAY [NEW."Produktnummer", OLD."Produktnummer"]
        END
    );
RETURN NULL;
END;
$$;
CREATE TRIGGER "trg_kundenrezension_rating"
AFTER
INSERT
    OR DELETE
    OR
UPDATE OF "Punkte",
    "Produktnummer" ON "Kundenrezension" FOR EACH ROW EXECUTE FUNCTION "aktualisiere_produkt_rating"();
-- Views
CREATE VIEW "ÄhnlicheProdukteBidirektional" AS
SELECT "Produktnummer1" AS "Produktnummer",
    "Produktnummer2" AS "ÄhnlicheProduktnummer"
FROM "Produktähnlichkeit"
UNION
SELECT "Produktnummer2" AS "Produktnummer",
    "Produktnummer1" AS "ÄhnlicheProduktnummer"
FROM "Produktähnlichkeit";
-- Indizes um Anfragen zu beschleunigen
CREATE INDEX "idx_produkt_typ" ON "Produkt" ("Produkttyp");
CREATE INDEX "idx_produkt_verkaufsrang" ON "Produkt" ("Verkaufsrang");
CREATE INDEX "idx_kategorie_oberkategorie" ON "Kategorie" ("OberkategorieID");
CREATE INDEX "idx_produktkategorien_kategorie" ON "Produktkategorien" ("KategorieID");
CREATE INDEX "idx_buchautoren_autor" ON "Buchautoren" ("AutorID");
CREATE INDEX "idx_buchverlage_verlag" ON "Buchverlage" ("VerlagID");
CREATE INDEX "idx_musik_cd_labels_label" ON "MusikCDLabels" ("LabelID");
CREATE INDEX "idx_beteiligte_personen_person" ON "Beteiligte Personen" ("PersonID");
CREATE INDEX "idx_beteiligte_kuenstler_kuenstler" ON "Beteiligte Künstler" ("KünstlerID");
CREATE INDEX "idx_produktähnlichkeit_p2" ON "Produktähnlichkeit" ("Produktnummer2");
CREATE INDEX "idx_produktstudios_studio" ON "Produktstudios" ("StudioID");
CREATE INDEX "idx_produktlistmania_liste" ON "ProduktListmania" ("ListmaniaID");
CREATE INDEX "idx_produktaudio_produkt" ON "Produktaudio" ("Produktnummer");
CREATE INDEX "idx_konditionen_produkt" ON "Konditionen" ("Produktnummer");
CREATE INDEX "idx_konditionen_filiale" ON "Konditionen" ("FilialeID");
CREATE INDEX "idx_kundenrezension_produkt" ON "Kundenrezension" ("Produktnummer");
CREATE INDEX "idx_kundenrezension_kunde" ON "Kundenrezension" ("KundeID");
CREATE INDEX "idx_kundenrezension_datum" ON "Kundenrezension" ("Rezensionsdatum");
CREATE INDEX "idx_kauf_kunde" ON "Kauf" ("KundeID");
CREATE INDEX "idx_kaufposition_produkt" ON "Kaufposition" ("Produktnummer");